steps:
  # Step 1: Build Docker image dari Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/clusterTools', '.']

  # Step 2: Push Docker image ke Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/clusterTools']

  # Step 3: Deploy ke Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'flask-app-service-account',
      '--image', 'gcr.io/$PROJECT_ID/clusterTools',
      '--region', 'asia-southeast2',  # Ubah sesuai lokasi server yang Anda pilih
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'SECRET_KEY=a1b2c3d4e5f67890abcd1234ef567890,GCS_BUCKET_NAME=my-app-uploads-bucket'
    ]

substitutions:
  _SERVICE_NAME: 'your-service-name'
  _IMAGE_NAME: 'clusterTools'